/Xenon/geometry/SetGasPressure 1.199 bar
/gasModelParameters/degrad/thermalenergy 10. eV
/Xenon/geometry/SetMainGas Xe
/Xenon/geometry/SetSecondGas CH4
/Xenon/geometry/SetThirdGas CO2
/Xenon/geometry/SetImpurityGas H2O
/Xenon/geometry/SetMainGasPercentage 100
/Xenon/geometry/SetSecondGasPercentage 0
/Xenon/geometry/SetThirdGasPercentage 0
/Xenon/geometry/SetImpurityGasPercentage 0
/run/numberOfThreads 1
/control/cout/ignoreThreadsExcept 0
#/control/cout/setCoutFile output.dmp
/Xenon/phys/setLowLimitE 20. eV
/Xenon/phys/InitializePhysics emlivermore
/Xenon/phys/InitializePhysics decay 
/Xenon/phys/AddParametrisation
/process/em/AddPAIRegion all GasRegion PAIphoton

#/random/setSeeds 0 0
/run/initialize

#/param/InActivateModel DegradModel
/param/InActivateModel GarfieldVUVPhotonModel

/analysis/setFileName test

####################################
############ Verbosities ###########
####################################
/tracking/verbose 0
/run/verbose 1
/event/verbose 1
/vis/verbose 0
####################################
########### Visualization ##########
####################################
#/vis/open VRML2FILE
#/vis/open OGL 600x600-0+0
/vis/open OGLIXm
# Draw geometry:
/vis/drawVolume
/vis/scene/add/trajectories smooth
/vis/scene/add/hits
/vis/viewer/set/lightsThetaPhi 90. 0.
/vis/viewer/set/viewpointThetaPhi 150. 90.
/vis/viewer/set/style surface
/vis/viewer/set/hiddenEdge true
# Draw smooth trajectories at end of event.
# Gamma-rays represented in red.
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- green
#/vis/modeling/trajectories/drawByParticleID-0/verbose 1
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/set 0 green
/vis/modeling/trajectories/drawByCharge-0/set -1 red
/vis/modeling/trajectories/drawByCharge-0/verbose 1
/vis/modeling/trajectories/drawByCharge-0/set 1 blue
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts false
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
/vis/modeling/trajectories/drawByCharge-0/default/setDrawAuxPts false


/vis/scene/endOfEventAction accumulate 1
#/vis/scene/endOfRunAction accumulate
/vis/geometry/set/forceWireframe collimatorLogical -1 1
/vis/geometry/set/forceWireframe collimatorLogical2 -1 1
/vis/geometry/set/forceWireframe windowLogical -1 1
/vis/geometry/set/forceWireframe detectorLogical -1 1
/vis/geometry/set/forceWireframe macorLogical -1 1
/vis/geometry/set/forceWireframe pmtLogical -1 1
/tracking/storeTrajectory 1

/gps/position 0. 0. 0. cm
/gps/direction 0. 1. 0 
/gps/particle gamma
/gps/ene/type Mono
/gps/ene/mono 6.9 keV

/run/beamOn 1

